spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/Step2
    username: root
    password: P@ssw0rd
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8080